sudo: required
services:
        - docker

before_install:
        - docker build -t smh/docker-react -f Dockerfile.dev .
          

scripts:
        - docker run smh/docker-react npm run test -- --coverage


